### ISSUE TITLE
Stopping and restarting the stream fails

### ISSUE THREAD

**Issue by kbingham** [raspberrypi/libcamera#12]
When stopping the stream, and restarting the stream does not successfully resume.

This can be tested with the new QCam toolbar additions.
A stop/start button is provided which halts the stream, and then restarts it.

The same methods are used when switching between cameras (for instance if a second UVC camera is attached) where the following will fail:
 - Start streaming on imx219
 - Switch streaming to UVC camera
 - Switch streaming to imx219
   *** Pipeline fails

> 
> Switching to camera imx219 0-0010
> [0:04:02.092516103] [1054] INFO Camera camera.cpp:750 configuring streams: (0) 800x600-0x34324152
> [0:04:02.113441286] [1054]  ERR V4L2 v4l2_videodevice.cpp:983 /dev/video15[cap]: Buffers already allocated
> [0:04:02.113587255] [1054]  ERR RPI raspberrypi.cpp:461 Failed to export ISP Output 1 buffers
> [0:04:02.113966026] [1054]  ERR RPI raspberrypi.cpp:589 Failed to allocate buffers
> Failed to start capture

**Comment by chrizbee** [comment]
@kbingham Does this still work for you?
Whenever I stop and restart the stream it will not resume... (tested with qcam).
