### ISSUE TITLE
Raspberry Pi Camera Module 3 not available on RPi 5/bookworm

### ISSUE THREAD

**Issue by gatonero** [raspberrypi/libcamera#120]
I can't get Raspberry Pi Camera Module 3 running on a RPi 5/bookworm. 

What I did:

- Test the camera on a RPi 4 /bullseye -> working
- Fresh installation of Raspberry Pi OS (64-bit)/bookworm on RPi 5
- Running `sudo apt update && sudo apt full-upgrade -y`.

cs@rpi5:~/prg/libcamera $ `libcamera-hello --list-cameras
` -> No cameras available!

Also there is no option under raspi-config -> Interface Options for camera

 I also set in /boot/firmware/config.txt camera_auto_detect=0 
and at the very end after [all] dtoverlay=imx708.

 Here is my system information 
[rpi5-systeminfo.txt](https://github.com/raspberrypi/libcamera/files/14545924/rpi5-systeminfo.txt)

Valid until 2024-03-10: [https://paste.debian.net/1310011](url)

**Comment by aallan** [comment]
Sounds more like a question for [the forums](https://forums.raspberrypi.com/viewforum.php?f=43) rather than one around `libcamera`.

**Comment by gatonero** [comment]
@aallan Thank you, I posted it in the suggested forum. I will close this issue here.

**Comment by gatonero** [comment]
I posted it here https://forums.raspberrypi.com/viewtopic.php?p=2201635#p2201635
