### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by pradyxdev** [raspberrypi/libcamera#137]
**OS :** Dietpi x64
**Device :** Raspberry pi 4

I have already tried reinstalling jinja2 via pip

**Command :** 
ninja -C build install

**Error :** 

ninja: Entering directory `build'                                                              [2/3] Generating Documentation/documentation with a custom command                             FAILED: Documentation/html                                                                     /usr/bin/sphinx-build -D release=v0.2.0+150-2031e2f2 -q -W -b html /home/dietpi/libcamera/Documentation Documentation/html                                                                    Traceback (most recent call last):                                                               File "/usr/bin/sphinx-build", line 33, in <module>                                               sys.exit(load_entry_point('Sphinx==3.4.3', 'console_scripts', 'sphinx-build')())             File "/usr/bin/sphinx-build", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 43, in <module>
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/usr/lib/python3/dist-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/usr/lib/python3/dist-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/usr/local/lib/python3.9/dist-packages/jinja2/__init__.py)
ninja: build stopped: subcommand failed.

**Output from mesa :**

The Meson build system                                                                                                                                                 Version: 1.0.0                                                                                                                                                         Source dir: /home/dietpi/libcamera                                                                                                                                     Build dir: /home/dietpi/libcamera/build                                                                                                                                Build type: native build                                                                                                                                               Project name: libcamera                                                                                                                                                Project version: 0.2.0                                                                                                                                                 C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")                                                                                C linker for the host machine: cc ld.bfd 2.35.2                                                                                                                        C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")                                                                            C++ linker for the host machine: c++ ld.bfd 2.35.2                                                                                                                     Host machine cpu family: aarch64                                                                                                                                       Host machine cpu: aarch64                                                                                                                                              Header "unistd.h" has symbol "issetugid" : NO (cached)                                                                                                                 Header "locale.h" has symbol "locale_t" : YES (cached)                                                                                                                 Header "sys/mman.h" has symbol "memfd_create" : YES (cached)                                                                                                           Header "stdlib.h" has symbol "secure_getenv" : YES (cached)                                                                                                            Compiler for C supports arguments -Wno-c99-designator: NO (cached)                                                                                                     Found pkg-config: /usr/bin/pkg-config (0.29.2)                                                                                                                         Found CMake: /usr/bin/cmake (3.18.4)                                                                                                                                   Run-time dependency lttng-ust found: NO (tried pkgconfig and cmake)                                                                                                    Program ./parser.py found: YES (/home/dietpi/libcamera/utils/ipc/./parser.py)                                                                                          Program ./generate.py found: YES (/home/dietpi/libcamera/utils/ipc/./generate.py)                                                                                      Program ./extract-docs.py found: YES (/home/dietpi/libcamera/utils/ipc/./extract-docs.py)                                                                              Program ./gen-tp-header.py found: YES (/home/dietpi/libcamera/utils/tracepoints/./gen-tp-header.py)                                                                    Configuring version.h using configuration                                                                                                                              Program openssl found: YES (/usr/bin/openssl)                                                                                                                          Library atomic found: YES                                                                                                                                              Dependency threads found: YES unknown (cached)
Dependency libdw found: YES 0.183 (cached)
Dependency libunwind found: YES 1.3.2 (cached)
Header "execinfo.h" has symbol "backtrace" : YES (cached)                                                                                                              Checking for function "dlopen" : NO (cached)
Library dl found: YES
Dependency libudev found: YES 247 (cached)
Dependency yaml-0.1 found: YES 0.2.2 (cached)
Run-time dependency gnutls found: NO (tried pkgconfig and cmake)                                                                                                       Dependency libcrypto found: YES 1.1.1w (cached)
Dependency libexif skipped: feature android disabled                                                                                                                   Dependency libjpeg skipped: feature android disabled                                                                                                                   Dependency libevent_pthreads found: YES 2.1.12-stable (cached)                                                                                                         
Dependency libtiff-4 found: YES 4.2.0 (cached)
Run-time dependency GTest found: NO (tried pkgconfig and system)                                                                                                       Looking for a fallback subproject for the dependency gtest                                                                                                             
Executing subproject gtest

gtest| Project name: gtest
gtest| Project version: 1.11.0
gtest| C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")                                                                     gtest| C++ linker for the host machine: c++ ld.bfd 2.35.2                                                                                                              gtest| Dependency threads found: YES unknown (cached)                                                                                                                  gtest| Dependency threads found: YES unknown (cached)                                                                                                                  gtest| Dependency threads found: YES unknown (cached)                                                                                                                  gtest| Dependency threads found: YES unknown (cached)                                                                                                                  gtest| Build targets in project: 56
gtest| Subproject gtest finished.

Dependency gtest from subproject subprojects/googletest-release-1.11.0 found: YES 1.11.0                                                                               Run-time dependency libdrm found: NO (tried pkgconfig and cmake)                                                                                                       Dependency libjpeg found: YES 2.0.6 (cached)
sdl2-config found: NO
Run-time dependency sdl2 found: NO (tried pkgconfig and config-tool)                                                                                                   Run-time dependency qt5 (modules: Core, Gui, Widgets) found: YES 5.15.2 (pkg-config)                                                                                   Header "QOpenGLWidget" has symbol "QOpenGLWidget" with dependencies Qt5Core, Qt5Core, Qt5Gui, Qt5Widgets: YES (cached)                                                 Detecting Qt5 tools
Run-time dependency qt5 (modules: Core) found: YES 5.15.2 (pkg-config)                                                                                                 Program /usr/lib/aarch64-linux-gnu/qt5/bin/moc found: YES 5.15.2 (/usr/lib/aarch64-linux-gnu/qt5/bin/moc)                                                              Program /usr/lib/aarch64-linux-gnu/qt5/bin/uic found: YES 5.15.2 (/usr/lib/aarch64-linux-gnu/qt5/bin/uic)                                                              Program /usr/lib/aarch64-linux-gnu/qt5/bin/rcc found: YES 5.15.2 (/usr/lib/aarch64-linux-gnu/qt5/bin/rcc)                                                              Program /usr/lib/aarch64-linux-gnu/qt5/bin/lrelease found: YES 5.15.2 (/usr/lib/aarch64-linux-gnu/qt5/bin/lrelease)                                                    Dependency glib-2.0 found: YES 2.66.8 (cached)
Dependency gstreamer-video-1.0 found: YES 1.18.4 (cached)                                                                                                              Dependency gstreamer-allocators-1.0 found: YES 1.18.4 (cached)                                                                                                         Dependency python3 found: YES 3.9 (cached)
Dependency pybind11 found: YES 2.6.2 (cached)
Program doxygen found: YES (/usr/bin/doxygen)
Program dot found: YES (/usr/bin/dot)
Configuring Doxyfile using configuration
Program sphinx-build-3 found: NO
Program sphinx-build found: YES (/usr/bin/sphinx-build)                                                                                                                Configuring config.h using configuration
Program python3 (jinja2, ply, jinja2, yaml) found: YES (/usr/bin/python3) modules: jinja2, ply, jinja2, yaml                                                           Build targets in project: 70

libcamera 0.2.0

  Versions
    Sources                  : 0.2.0+150-2031e2f2                                                                                                                      
  Paths
    LIBCAMERA_DATA_DIR       : "/usr/local/share/libcamera"                                                                                                                LIBCAMERA_SYSCONF_DIR    : "/usr/local/etc/libcamera"                                                                                                                  IPA_PROXY_DIR            : "/usr/local/libexec/libcamera"                                                                                                              IPA_CONFIG_DIR           : "/usr/local/etc/libcamera/ipa:/usr/local/share/libcamera/ipa"                                                                               IPA_MODULE_DIR           : "/usr/local/lib/aarch64-linux-gnu/libcamera"                                                                                            
  Configuration
    SoftISP support          : True
    IPA modules signed with  : libcrypto
    Enabled pipelines        : imx8-isi
                               mali-c55
                               rkisp1
                               rpi/vc4
                               simple
                               uvcvideo
    Enabled IPA modules      : rkisp1
                               rpi/vc4
                               simple
    Controls files           : control_ids_draft.yaml                                                                                                                                                 control_ids_core.yaml                                                                                                                                                  control_ids_rpi.yaml                                                                                                                        Properties files         : property_ids_draft.yaml                                                                                                                                                property_ids_core.yaml                                                                                                                      Hotplug support          : YES
    Tracing support          : NO
    Android support          : NO
    GStreamer support        : YES
    Python bindings          : YES
    V4L2 emulation support   : NO
    cam application          : YES
    qcam application         : YES
    lc-compliance application: YES
    Unit tests               : NO

  Subprojects
    gtest                    : YES

  User defined options
    pycamera                 : enabled

Found ninja-1.10.1 at /usr/bin/ninja

**Comment by naushir** [comment]
It seems you have a problem with the documentation dependencies for the libcamera build.  Can you try disabling documentation (``-Ddocumentation=disabled``) in your meson config and try again?

**Comment by naushir** [comment]
Any updates on this?  If not I'll close this shortly.
