### ISSUE TITLE
No Camera Available after installing libcamera

### ISSUE THREAD

**Issue by birdboxers** [raspberrypi/libcamera#149]
Hello, I am working on a project that involves a raspberry pi model 4b (running on raspberry pi os 64 bit bookworm) to take photos every 3 minutes and store them in a USB drive. It was working perfectly, i was using libcamera stills and cron- and then I tried to get libcamera so that it can also live stream this footage at the same time on youtube. I was unable to find the libcamera executable file, and after EVERYTHING like the meson setup, ninja build, ninja -C build install, like all possible variations it was just making .so libcamera files and therefore the libcamera command wasn't working. Anyways then I went to the USB folder (where it was perfectly taking photos using libstill before) and it wasn't taking photos? it was saying no cameras available on the terminal (the camera was connected in the same way untouched), and then i tried to remove libcamera (not libcamera stills) and tried; it still said that?? Did i like completely mess up everything i really don't know what the actual heck is going on I'm sooooo confused please help

**Comment by naushir** [comment]
``rpicam-apps`` (formerly named ``libcamera-apps``) are not built as part of this repo.  They can be found at https://github.com/raspberrypi/rpicam-apps.  You can find full instructions for building them at https://www.raspberrypi.com/documentation/computers/camera_software.html#rpicam-apps.

Hope this answers your questions.  If not, do let us know.
