### ISSUE TITLE
How to resolve the libcamera interface=0 error

### ISSUE THREAD

**Issue by LibraX7** [raspberrypi/libcamera#152]
when I use the debian to call the camera ，the libcamera tell me there is no camera find ，but the pi can detect camera.I use vcgencmd_get_camera ,the result is supported=1 ,detected=1,libcamera interfaces=0,how can i resolve it

**Comment by 6by9** [comment]
[What to do if your camera is not detected](https://forums.raspberrypi.com/viewtopic.php?p=2175868#p2175868)

> You can tell if a tutorial is talking about the obsolete camera stack if you see the following:
>
>    Command line applications such as: raspistill, raspivid
>    **Use of "vc_gencmd get_camera"**
