### ISSUE TITLE
setting exposure time with libcamerasrc and gstreamer

### ISSUE THREAD

**Issue by bryangd34** [raspberrypi/libcamera#168]
Is there a way to set exposure with libcamerasrc and gstreamer?

I suspect not, but before I give up I thought I would ask.

`gst-inspect-1.0 libcamerasrc`

> Plugin Details:
>   Name                     libcamera
>   Description              libcamera capture plugin
>   Filename                 /home/bryangd/Desktop/libcamera/build/src/gstreamer/libgstlibcamera.so
>   Version                  0.3.0+65-6ddd79b5
>   License                  LGPL
>   Source module            libcamera
>   Binary package           libcamera
>   Origin URL               https://libcamera.org

...

and a bit further down I see these elements:

> Element Properties:
> 
>   auto-focus-mode     : Available options: AfModeManual, AfModeAuto or AfModeContinuous.
>                         flags: writable
>                         Enum "GstLibcameraAutoFocus" Default: 0, "manual-focus"
>                            (0): manual-focus     - AfModeManual
>                            (1): automatic-auto-focus - AfModeAuto
>                            (2): continuous-auto-focus - AfModeContinuous Write only
>   
>   camera-name         : Select by name which camera to use.
>                         flags: readable, writable, changeable only in NULL or READY state
>                         String. Default: null
>   
>   name                : The name of the object
>                         flags: readable, writable
>                         String. Default: "libcamerasrc0"
>   
>   parent              : The parent of the object
>                         flags: readable, writable
>                         Object of type "GstObject"
> 

So no exposure...

Using rpicam-still:
`rpicam-still --shutter 4000 --camera 0`

I can control exposure, so was hoping to be able to do something similar using gstreamer.
Any help/ideas/thoughts would be great. Thanks.

**Comment by naushir** [comment]
I think there is work in progress on this topic on the libcamera mailing list, see the patches at:
https://patchwork.libcamera.org/project/libcamera/list/?series=451

This is not a bit of work that I'm actively involved with, so I suggest keeping track on the libcamera-devel list.
