### ISSUE TITLE
Error when running two IMX708 on Raspberrypi5 at the same time

### ISSUE THREAD

**Issue by tom-ard** [raspberrypi/libcamera#179]
**Kernel version**
![image](https://github.com/user-attachments/assets/322b23aa-826b-4794-9ec7-3999f6e9bc6f)
**libcamera version**
![image](https://github.com/user-attachments/assets/3ad51b23-72f3-4166-9ac9-562bc06f5d84)
When I run two IMX708 cameras at the same time, the camera that starts last always reports the error "Unable to set controls: Device or resource busy".
But it can auto focus normally.
![image](https://github.com/user-attachments/assets/3f133486-6acf-4db5-b870-2817f33a2e92)

**Comment by naushir** [comment]
Please ignore this error - it is inconsequential.  I will look to remove it - actually I though I already did, so I'll need to check that.
