### ISSUE TITLE
IMX296 IMX 334 support

### ISSUE THREAD

**Issue by ychwang** [raspberrypi/libcamera#182]
can libcamera support IMX296 or IMX334 sonser

**Comment by naushir** [comment]
IMX296 is natively supported by the Raspberry Pi libcamera implementation. 

IMX334 is not.  You will need a kernel driver and additional support in libcamera (camera helper and tuning files) to get it working.

**Comment by ychwang** [comment]
> IMX296 is natively supported by the Raspberry Pi libcamera implementation.
> 
> IMX334 is not. You will need a kernel driver and additional support in libcamera (camera helper and tuning files) to get it working.



> IMX296 is natively supported by the Raspberry Pi libcamera implementation.
> 
> IMX334 is not. You will need a kernel driver and additional support in libcamera (camera helper and tuning files) to get it working.

Thanks

**Comment by 6by9** [comment]
It does already have a kernel driver, but with the full res mode running at a link frequency of 891MHz / 1.782Gbit/s it exceeds the spec for Pi5 (1.5Gbit/s). It may work, but no guarantees. Reworking clock structures is possible, but generally needs the datasheet.

**Comment by ychwang** [comment]
I get it.Imx296 is my target cmos. Imx334&nbsp; the image is to large,my program deal is not fit my soulution.So,Imx296 is my best choose.Thank you very much.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月29日(星期天) 下午4:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [raspberrypi/libcamera] IMX296 IMX 334 support (Issue #182)














 
It does already have a kernel driver, but with the full res mode running at a link frequency of 891MHz / 1.782Gbit/s it exceeds the spec for Pi5 (1.5Gbit/s). It may work, but no guarantees. Reworking clock structures is possible, but generally needs the datasheet.
