### ISSUE TITLE
How to specify correct Overlay for ARDUCAM (IMX219)

### ISSUE THREAD

**Issue by git2212** [raspberrypi/libcamera#187]
am trying to add ARDUCAM (IMX219) support to my Klipper setup on an OrangepiZero 3 running an Octoprint frontend. Since the recommended OS was an Armbian Bookworm image, that's what I installed... as a result most of the "guides" out there targeted at PI seem to not apply.

I want to use Octoprint's support for camera-streamer with camera support via libcamera so I went ahead and installed the available APT packages

libcamera0.3 libcamera-tools libcamera-v4l2. 

How do I specify the correct overlays for libcamera on armbian?... dtoverlay which is common for PIs seems not to exists on armbian, will the following in /boot/armbianEnv.txt do it?

`overlays=imx219`

Thx

**Comment by naushir** [comment]
We won't able to answer support queries for non Raspberry Pi platforms. Please seek support with your vendor.
