### ISSUE TITLE
directly  get gray images

### ISSUE THREAD

**Issue by leeyunjie** [raspberrypi/libcamera#188]
How to use libcamera code to configure IMX296LLR camera to directly output gray images?

**Comment by naushir** [comment]
rpicam-apps will support this out of the box. What seems to be the problem here?

**Comment by leeyunjie** [comment]
> rpicam-apps will support this out of the box. What seems to be the problem here?
Naushir， Thank you for your prompt response！

But the Bookworm system does not support rpicam apps.

**Comment by naushir** [comment]
Are you using Rasberry Pi OS? If so, bookworm comes with rpicam-apps installed by default.

**Comment by naushir** [comment]
Is there anything more to do for this?  If not, I'll close this shortly.
