### ISSUE TITLE
libcamera-still image quality much better than my c++ based app

### ISSUE THREAD

**Issue by muttistefano** [raspberrypi/libcamera#195]
Hi all,
I am developing a C++ app with a quadroscopic 1MP global shutter camera board on RPI5.
I noticed that by default, libcamera-still quality is much better than the picture I acquired with my code.
Does libcamera-still use some configuration by default?
I am not currently modifying any control parameters in my code.
Is there a way to get libcamera-still default parameters to understand how to tune mine? 
thanks

**Comment by naushir** [comment]
Can you post some example images showing the differences?

**Comment by muttistefano** [comment]
Hi, 
this is the one captured from the quadrascopic camera arducam using "libcamera-still -t 500 -n -o test.jpg"
![test](https://github.com/user-attachments/assets/1f76e267-7bb3-48c6-a332-d3911b7e9d4e)

while these ones are captured using the a c++ app made using libcamera API:
![image](https://github.com/user-attachments/assets/8e0e6f8d-7c1d-4429-8c57-e92c1e6fe3ed)
![image2](https://github.com/user-attachments/assets/2c034197-684f-4fa5-8c27-295c19df9d13)
![image3](https://github.com/user-attachments/assets/a7c688ad-36b9-4445-897f-f2d4156a145a)
![image4](https://github.com/user-attachments/assets/b7475b32-1000-4e7d-9bdf-1f1072f3a9a2)

I tried tweaking with auto exposure, flickering control, and brightness, but I can achieve the same quality.
Plus, it seems like there is some tearing in the one I acquired with the API.
Thanks

**Comment by naushir** [comment]
Which libcamera library are you using?  Is it supplied by Arducam or the Raspberry Pi supplied one?

**Comment by muttistefano** [comment]
I am using the one patched by arducam.

**Comment by naushir** [comment]
Have you tried the Raspberry Pi libcamera packages instead?  I'm afraid I don't know what Arducam do in their version of libcamera, so it would be best to ask them for assistance.

**Comment by muttistefano** [comment]
Well I tought the normal libcamera won't work with their module because they provide a board that merges 4 cameras (https://www.arducam.com/product/arducam-1mp4-quadrascopic-camera-bundle-kit-for-raspberry-pi-nvidia-jetson-nano-xavier-nx-four-ov9782-global-shutter-color-camera-modules-and-camarray-camera-hat-b0331/)
I am also in contact with them.
Thanks

**Comment by 6by9** [comment]
> quadrascopic camera arducam

Presumably the quad OV9281 https://www.uctronics.com/arducam-1mp-4-quadrascopic-camera-bundle-kit-for-raspberry-pi-nvidia-jetson-nano-xavier-nx-four-ov9281-global-shutter-monochrome-camera-modules-and-camarray-camera-hat.html
It's not supported by the standard  libcamera.

The Arducam board is doing some significant data manipulation to combine the 4 images into one, so support needs to come from them. There's very little that Raspberry Pi can do to support it.

The individual images you've captured just look under-exposed. Have you given AE time to adapt?

**Comment by naushir** [comment]
Agree, it looks like the images are simply underexposed.  But I can't tell what/how the statistics are generated and used on a 4x combined image like this.  This is definitely something you need to speak to Arducam about.

**Comment by muttistefano** [comment]
I will post here for reference if arducam comes back with news.
Thanks all.
