### ISSUE TITLE
Stereo camera

### ISSUE THREAD

**Issue by SinemVisea** [raspberrypi/libcamera#202]
Hello, I am using a Waveshare stereo camera. I am working on a Raspberry Pi 5.

I am following the setup instructions from this link: https://www.waveshare.com/wiki/IMX219-83_Stereo_Camera#Working_with_Raspberry_Pi_5_.28libcamera.29

One of my cameras works while the other one does not.

The outputs I received:
--------------------------------------------------------------------------------------------------------
Registered camera /base/axi/pcie@120000/rp1/i2c@80000/imx219@10 to CFE device /dev/media3 and ISP device /dev/media2 using PiSP variant BCM2712_C0
Made X/EGL preview window
Postprocessing requested lores: 640x640 BGR888
Reading post processing stage "hailo_yolo_inference"
Reading post processing stage "object_detect_draw_cv"
Mode selection for 1640:1232:12:P
    SRGGB10_CSI2P,640x480/0 - Score: 4504.81
    SRGGB10_CSI2P,1640x1232/0 - Score: 1000
    SRGGB10_CSI2P,1920x1080/0 - Score: 1541.48
    SRGGB10_CSI2P,3280x2464/0 - Score: 1718
    SRGGB8,640x480/0 - Score: 5504.81
    SRGGB8,1640x1232/0 - Score: 2000
    SRGGB8,1920x1080/0 - Score: 2541.48
    SRGGB8,3280x2464/0 - Score: 2718
Stream configuration adjusted
--------------------------------------------------------------------------------------------------------
Sensor: /base/axi/pcie@120000/rp1/i2c@88000/imx219@10 - Selected sensor format: 1640x1232-SBGGR10_1X10 - Selected CFE format: 1640x1232-PC1B
--------------------------------------------------------------------------------------------------------

I reinstalled the operating system and checked the cables. Do you have any suggestions for me? 
What can I do to get the other camera to work as well? Can you help me?

**Comment by naushir** [comment]
You have to select the camera to use with the ``--camera`` command line argument.  For further queries, please get support directly from Waveshare for this camera as it is not something we directly support.
