### ISSUE TITLE
Unable to build: src/libcamera/meson.build:70:0: ERROR: Dependency "yaml-0.1" not found, tried pkgconfig

### ISSUE THREAD

**Issue by skotwani** [raspberrypi/libcamera#21]
Get the error below when trying to run a build from the picamera2 branch. I was following instructions from https://www.raspberrypi.com/news/a-preview-release-of-the-picamera2-library/ which was dated 2/15/22. Checking out the commit from that date and building worked just fine.

The Meson build system
Version: 0.62.1
Source dir: /home/pi/libcamera
Build dir: /home/pi/libcamera/build
Build type: native build
Project name: libcamera
Project version: 0.0.0
C compiler for the host machine: cc (gcc 10.2.1 "cc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110")
C linker for the host machine: cc ld.bfd 2.35.2
C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110")
C++ linker for the host machine: c++ ld.bfd 2.35.2
Host machine cpu family: arm
Host machine cpu: armv7l
Header <unistd.h> has symbol "issetugid" : NO 
Header <stdlib.h> has symbol "secure_getenv" : YES 
Compiler for C supports arguments -Wno-c99-designator: NO 
Library lttng-ust found: NO
Program ./parser.py found: YES (/home/pi/libcamera/utils/ipc/./parser.py)
Program ./generate.py found: YES (/home/pi/libcamera/utils/ipc/./generate.py)
Program ./extract-docs.py found: YES (/home/pi/libcamera/utils/ipc/./extract-docs.py)
Program ./gen-tp-header.py found: YES (/home/pi/libcamera/utils/tracepoints/./gen-tp-header.py)
Configuring version.h using configuration
Program openssl found: YES (/usr/bin/openssl)
Library atomic found: YES
Library libdw found: YES
Library libunwind found: YES
Header <execinfo.h> has symbol "backtrace" : YES 
Run-time dependency threads found: YES
Library dl found: YES
Library gnutls found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency libudev found: NO (tried pkgconfig and cmake)
Run-time dependency yaml-0.1 found: NO (tried pkgconfig)

src/libcamera/meson.build:70:0: ERROR: Dependency "yaml-0.1" not found, tried pkgconfig

A full log can be found at /home/pi/libcamera/build/meson-logs/meson-log.txt
ninja: Entering directory `build'
ninja: error: loading 'build.ninja': No such file or directory
ninja: Entering directory `build'
ninja: error: loading 'build.ninja': No such file or directory

**Comment by dinapappor** [comment]
Looks like  you are also missing cmake.

Can you try `apt-get --no-install-recommends install cmake libyaml-dev` ?

**Comment by eli-schwartz** [comment]
cmake is not needed...

**Comment by skotwani** [comment]
I added that to my build steps and that error is now gone. I now have separate issue (ModuleNotFoundError: No module named 'qt_gl_preview') but that probably deserves a separate issue. Thank you!
