### ISSUE TITLE
Building libcamera on the RPiv4 seems to crash the RPi

### ISSUE THREAD

**Issue by kbingham** [raspberrypi/libcamera#3]
Not yet sure if this is a heat thing, a memory thing (this is a lower memory device) or because I have non-fully-tested firmwares loaded (from issue:1 here).

I can't attach a serial console at present so I can't easily see if there's a kernel panic. Just logging here for insight if anyone has any.

Next step will be reboot and get meson (ninja) to build only one job at a time.

**Comment by meawoppl** [comment]
As a side note to this all, the build is -faster- and maybe 10x less memory hungry if you use clang ala:
```
CC=clang-11 CXX=clang++-11 meson build -Dpipelines=raspberrypi -Dtest=false -Dv4l2=true -Dpycamera=enabled
ninja -C build -j1
```
I was able to complete the build on a pi zero this way in about 20mins.
