### ISSUE TITLE
Anyway to add crosshair overlay to libcamera-hello preview?

### ISSUE THREAD

**Issue by TeeKKar** [raspberrypi/libcamera#32]
I am trying to add a crosshair so I can center my raspberry camera, is there any way I can do that?

**Comment by naushir** [comment]
Could you please open an issue in the libcamera-apps repo to discuss this?
https://github.com/raspberrypi/libcamera-apps/issues

Alternatively, you might want to look at picamera2 - which is likely to be easier to achieve what you want:
https://github.com/raspberrypi/picamera2
