### ISSUE TITLE
Reproducible builds | Libcamera

### ISSUE THREAD

**Issue by DesobedienteTecnologico** [raspberrypi/libcamera#34]
Hi!

I'm compiling libcamera from Buildroot and works great. The problem comes when I want to do reproducible builds from libcamera.
The library adds a random characters (I assume is some signature) when building.

- Is there a way to have reproducible builds without modifying any file under libcamera repository?
- Is unsafe under you point or view, disable the signature when building?

I saw this, and add as reference:
https://github.com/raspberrypi/libcamera/blob/main/src/libcamera/pub_key.cpp

Regards

**Comment by kbingham** [comment]
The public-key implementation is a core detail of libcamera's ability to validate if dynamically loaded IPA modules are supported or not. If they are not signed, they are expected to be sandboxed, and isolated.

This implementation could likely be extended to support externally supplied public and private keys in some form, which would make it 'reproducible'.

**Comment by DesobedienteTecnologico** [comment]
Thanks for your fast reply @kbingham.


It created confusion for me at some point, because I have made more than 4 buildings to check the file differences and still different "signature" in every build. Can be that probably still not reproducible even using the actual pub/priv keys used right now?

I will have a look in how to implement external supplied public and private keys.

Regards

**Comment by kbingham** [comment]
The private key is generated only once in a given build structure, so if you don't remove the build objects it should stay the same. But if you're building from clean, or in CI it will be a new key each time.
That's why you probably want a mechanism to provide the keys.
Or you could disable the signatures entirely and the modules will all be treated as external

**Comment by DesobedienteTecnologico** [comment]
Understand, thanks for all the information.
I will work on this.

If you think that implementation can be needed in this repository, I could do a PR once is done.

Regards @kbingham
