### ISSUE TITLE
minFrameDuration_ set to defaultMaxFrameDuration when not specified?

### ISSUE THREAD

**Issue by tewarid** [raspberrypi/libcamera#51]
I am looking into how frame durations are calculated and came across this line. Is it a typo that minFrameDuration_ is set to  defaultMaxFrameDuration when not specified?

https://github.com/raspberrypi/libcamera/blob/923f5d707bb760bd3e724b3373568fa88c68454f/src/ipa/raspberrypi/raspberrypi.cpp#L1460

**Comment by naushir** [comment]
That's a good catch!  I will send a patch to fix this.  

In practice, this is not a problem, as we never used the default values.
