### ISSUE TITLE
Using libcamerasrc and Gstreamer

### ISSUE THREAD

**Issue by yeric1789** [raspberrypi/libcamera#62]
Hardware: Raspberry Pi 4 8GB RAM
Camera: Camera Module 3 NoIR Wide, Camera V2.1
OS: (Bullseye) Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

Hi,

I am attempting to setup a stream from a Raspberry Pi 4, using gstreamer rather than libcamera-vid, to an external client. For test purposes I am attempting to run it locally for now.
I started off with a fresh install of the Raspberry Pi OS (32-bit) "Raspberry Pi OS with desktop and recommended software" found here:
 https://www.raspberrypi.com/software/operating-systems/

I then install gstreamer utilizing the following commands:
```
sudo apt-get install libx264-dev libjpeg-dev && \
sudo apt-get install libgstreamer1.0-dev \
libgstreamer-plugins-base1.0-dev \
libgstreamer-plugins-bad1.0-dev \
gstreamer1.0-plugins-ugly \
gstreamer1.0-tools \
gstreamer1.0-gl \
gstreamer1.0-gtk3
```

Then following the documentation found here: https://www.raspberrypi.com/documentation/computers/camera_software.html#using-gstreamer
I utilize the libcamerasrc element, using the command:
```
gst-launch-1.0 libcamerasrc ! capsfilter caps=video/x-raw,width=1280,height=720,format=NV12 ! v4l2convert ! v4l2h264enc extra-controls="controls,repeat_sequence_header=1" ! h264parse ! rtph264pay ! udpsink host=localhost port=5000
```

This is the same command on the published webpage:

I then see the following output:

```
user5@raspberrypi:~ $ gst-launch-1.0 libcamerasrc ! capsfilter caps=video/x-raw,width=1280,height=720,format=NV12 ! v4l2convert ! v4l2h264enc extra-controls="controls,repeat_sequence_header=1" ! h264parse ! rtph264pay ! udpsink host=localhost port=5000
Setting pipeline to PAUSED ...
[0:16:18.045171814] [6437]  INFO Camera camera_manager.cpp:299 libcamera v0.0.4+22-923f5d70
[0:16:18.173639384] [6438]  INFO RPI raspberrypi.cpp:1476 Registered camera /base/soc/i2c0mux/i2c@1/imx708@1a to Unicam device /dev/media2 and ISP device /dev/media1
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
[0:16:18.178883793] [6441]  INFO Camera camera.cpp:1028 configuring streams: (0) 1280x720-NV12
[0:16:18.179307367] [6438]  INFO RPI raspberrypi.cpp:851 Sensor: /base/soc/i2c0mux/i2c@1/imx708@1a - Selected sensor format: 1536x864-SBGGR10_1X10 - Selected unicam format: 1536x864-pBAA
Redistribute latency...
ERROR: from element /GstPipeline:pipeline0/v4l2h264enc:v4l2h264enc0: Failed to process frame.
Additional debug info:
../sys/v4l2/gstv4l2videoenc.c(828): gst_v4l2_video_enc_handle_frame (): /GstPipeline:pipeline0/v4l2h264enc:v4l2h264enc0:
Maybe be due to not enough memory or failing driver
Execution ended after 0:00:00.456343238
Setting pipeline to NULL ...
ERROR: from element /GstPipeline:pipeline0/GstLibcameraSrc:libcamerasrc0: Internal data stream error.
Additional debug info:
../src/gstreamer/gstlibcamerasrc.cpp(312): processRequest (): /GstPipeline:pipeline0/GstLibcameraSrc:libcamerasrc0:
streaming stopped, reason error (-5)
Freeing pipeline ...
```

I have tried multiple system configurations, with different SD cards and cameras modules (including older version 2 cameras) to no avail. I have updated software on other Raspberry pi 4's with the same results. 

Any help that could be provided would be greatly appreciated. 
Please let me know if you have any questions or need more info thanks.

See the attached debug file for GST_DEBUG=4l2*:7
[output_gstreamer_err.txt](https://github.com/raspberrypi/libcamera/files/11724483/output_gstreamer_err.txt)

I also found that it could be connected to this issue as well:
https://github.com/raspberrypi/firmware/issues/1701

**Comment by 6by9** [comment]
Your log does have
```
0:00:00.398923128 6m 6983m  0x1bbc0f0 7mDEBUG  m m        v4l2videoenc gstv4l2videoenc.c:581:gst_v4l2_video_enc_negotiate:<v4l2h264enc0>m Selected H264 profile baseline at level 1
```
which would imply that you haven't configured an appropriate level. (Level 1 is max 128×96@30.9fps, or 176×144@15.0fps).

Did you follow the advice in https://github.com/raspberrypi/firmware/issues/1701 of actually specifying the level?
```
gst-launch-1.0 libcamerasrc ! capsfilter caps=video/x-raw,width=1280,height=720,format=NV12 ! v4l2convert ! v4l2h264enc extra-controls="controls,repeat_sequence_header=1" ! 'video/x-h264,level=(string)4' ! h264parse ! rtph264pay ! udpsink host=localhost port=5000
```

**Comment by yeric1789** [comment]
Hi,

Thanks for the response.
The following command does seem to work:
```
gst-launch-1.0 libcamerasrc ! capsfilter caps=video/x-raw,width=1280,height=720,format=NV12 ! v4l2convert ! v4l2h264enc extra-controls="controls,repeat_sequence_header=1" ! 'video/x-h264,level=(string)4' ! h264parse ! rtph264pay ! udpsink host=localhost port=5000
```

However when I attempt to do what you suggest (removing v4l2convert) from the pipeline using the following command:
```
gst-launch-1.0 libcamerasrc ! capsfilter caps=video/x-raw,width=1280,height=720,format=NV12 ! v4l2h264enc extra-controls="controls,repeat_sequence_header=1" ! 'video/x-h264,level=(string)4' ! h264parse ! rtph264pay ! udpsink host=localhost port=5000
```

I get the following error:
```
Setting pipeline to PAUSED ...
[1:41:49.371601748] [7523]  INFO Camera camera_manager.cpp:299 libcamera v0.0.4+22-923f5d70
[1:41:49.486935187] [7524]  INFO RPI raspberrypi.cpp:1476 Registered camera /base/soc/i2c0mux/i2c@1/imx708@1a to Unicam device /dev/media2 and ISP device /dev/media1
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
[1:41:49.492085610] [7527]  INFO Camera camera.cpp:1028 configuring streams: (0) 1280x720-NV12
[1:41:49.492489829] [7524]  INFO RPI raspberrypi.cpp:851 Sensor: /base/soc/i2c0mux/i2c@1/imx708@1a - Selected sensor format: 1536x864-SBGGR10_1X10 - Selected unicam format: 1536x864-pBAA
ERROR: from element /GstPipeline:pipeline0/GstLibcameraSrc:libcamerasrc0: Internal data stream error.
Additional debug info:
../src/gstreamer/gstlibcamerasrc.cpp(312): processRequest (): /GstPipeline:pipeline0/GstLibcameraSrc:libcamerasrc0:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:00.396907607
Setting pipeline to NULL ...
Freeing pipeline ...
```

**Comment by 6by9** [comment]
> However when I attempt to do what you suggest (removing v4l2convert) from the pipeline using the following command:

C'est la vie.
AFAIK both v4l2convert and v4l2h264enc will give the same set of caps, so libcamerasrc should be happy. You've not given enough logging to diagnose it, and it's not something that I can run up immediately.

**Comment by landswellsong** [comment]
Try adding `format=YUY2,colorimetry=bt709,interlace-mode=progressive` to the capsfilter
Works fine for me and you also don't need the convert step this way

**Comment by naushir** [comment]
Closing this issue down now, feel free to reopen if this is still unresolved.
