### ISSUE TITLE
ModuleNotFoundError: No module named 'libcamera.utils'

### ISSUE THREAD

**Issue by zoldaten** [raspberrypi/libcamera#63]
cant start simple-continuous-capture.py as it asks for libcamera.utils
could you help ?

**Comment by naushir** [comment]
Did you manually compile/install components of libcamera or did you use the apt versions?  If the former, it may have caused some inconstencies with the installed system libraries.  If you could try with a fresh sd card image and use the pre-installed packages, you may find the error disappears.

**Comment by naushir** [comment]
Any further updates to this issue?  If not, ill close this down shortly.
