### ISSUE TITLE
Live Stream parallel to raw capture possible? 

### ISSUE THREAD

**Issue by Schaggo** [raspberrypi/libcamera#65]
Hey, 

I am trying to figure out what the best approach for a live viewer for my libcamera app is. 

Currently, I capture timed raw frames at full res 10bit raw on command.  
So the camera idles - I send a capture signal - the camera fills a predefined number of buffers and afterwards writes them to disk.
I would like to implement a way to see what I am capturing before the full raws are sent over - thus a live viewer / stream.

I am thinking about passing the image to a second thread that converts it to a lower res (m)jpg and push that over UDP. 
I am pretty sure that is a dumb idea, because the conversion of full res raw to another file format will take some time.

Is it possible to have a second stream with a different resolution/bitrate ?

What would be the best approach?

Thank you for your time

**Comment by aallan** [comment]
This sounds like a question best answered [on the forums](https://forums.raspberrypi.com/).

**Comment by Schaggo** [comment]
@aallan  Alright, sorry for the hustle.
