### ISSUE TITLE
ninja -C build install not working (even when running)

### ISSUE THREAD

**Issue by Daifaizonaldridge** [raspberrypi/libcamera#70]
I am doing the "Getting started - libcamera" instructions but when I run the ninja -C build install command, the command runs but everything is only halfway/not installed.

these are the error statments:
![Screenshot 2023-07-20 092629](https://github.com/raspberrypi/libcamera/assets/123976724/d4ddac38-768e-4b2d-bc2e-c570c15c7576)
![Screenshot 2023-07-20 092705](https://github.com/raspberrypi/libcamera/assets/123976724/35eaad1d-de9c-44f9-a244-b1ce082833fd)

**Comment by naushir** [comment]
Do you have any local changes to the libcamera tree?  Can you post the exact ``meson setup`` command you are using?

**Comment by Daifaizonaldridge** [comment]
yeah
![Screenshot 2023-07-20 101528](https://github.com/raspberrypi/libcamera/assets/123976724/dc4e4798-3142-409d-8f89-8a96a9d50807)

**Comment by naushir** [comment]
Can you delete your build directory and run the following command:
```
meson setup build --buildtype=release -Dpipelines=rpi/vc4 -Dipas=rpi/vc4 -Dv4l2=true -Dgstreamer=enabled -Dtest=false -Dlc-compliance=disabled -Dcam=disabled -Dqcam=disabled -Ddocumentation=disabled -Dpycamera=enabled
```
and attach the full output that is generated.

**Comment by Daifaizonaldridge** [comment]
Deleting build directory:
![Screenshot 2023-07-20 102754](https://github.com/raspberrypi/libcamera/assets/123976724/e5e0b22c-9039-43de-a034-c2b4de70a1a9)

doing your command:
![Screenshot 2023-07-20 102809](https://github.com/raspberrypi/libcamera/assets/123976724/3118635b-d588-41ef-be5f-77d651774e06)

**Comment by naushir** [comment]
Instead of ``meson setup --wipe libcamera`` please use something like ``rm -rf build`` to delete the directory and run the meson setup command again.

Instead of a screencap, can you copy-paste the text from the terminal window as it spans multiple pages.

**Comment by Daifaizonaldridge** [comment]
djaldridge@LAPTOP-4BBALQ2L:~$ ls
cs  fprime  fprime-visual  libcamera  node_modules  package-lock.json  package.json  vcpkg
djaldridge@LAPTOP-4BBALQ2L:~$ cd libcamera
djaldridge@LAPTOP-4BBALQ2L:~/libcamera$ rm -rf build
rm: cannot remove 'build/Documentation/html/docs.html': Permission denied
rm: cannot remove 'build/Documentation/html/python-bindings.html': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/getting-started.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/index.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/python-bindings.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/api-html/index.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/contributing.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/environment.pickle': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/sensor_driver_requirements.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/guides/ipa.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/guides/pipeline-handler.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/guides/tracing.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/guides/application-developer.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/guides/introduction.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/coding-style.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/docs.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/lens_driver_requirements.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/.doctrees/environment_variables.doctree': Permission denied
rm: cannot remove 'build/Documentation/html/_static/documentation_options.js': Permission denied
rm: cannot remove 'build/Documentation/html/_static/basic.css': Permission denied
rm: cannot remove 'build/Documentation/html/_static/searchtools.js': Permission denied
rm: cannot remove 'build/Documentation/html/_static/search.png': Permission denied
rm: cannot remove 'build/Documentation/html/_static/doctools.js': Permission denied
rm: cannot remove 'build/Documentation/html/_static/minus.png': Permission denied
rm: cannot remove 'build/Documentation/html/_static/jquery.js': Permission denied
rm: cannot remove 'build/Documentation/html/_static/pygments.css': Permission denied
rm: cannot remove 'build/Documentation/html/_static/file.png': Permission denied
rm: cannot remove 'build/Documentation/html/_static/css/theme.css': Permission denied
rm: cannot remove 'build/Documentation/html/_static/plus.png': Permission denied
rm: cannot remove 'build/Documentation/html/_static/language_data.js': Permission denied
rm: cannot remove 'build/Documentation/html/_static/underscore.js': Permission denied
rm: cannot remove 'build/Documentation/html/coding-style.html': Permission denied
rm: cannot remove 'build/Documentation/html/api-html/index.html': Permission denied
rm: cannot remove 'build/Documentation/html/searchindex.js': Permission denied
rm: cannot remove 'build/Documentation/html/contributing.html': Permission denied
rm: cannot remove 'build/Documentation/html/guides/ipa.html': Permission denied
rm: cannot remove 'build/Documentation/html/guides/tracing.html': Permission denied
rm: cannot remove 'build/Documentation/html/guides/application-developer.html': Permission denied
rm: cannot remove 'build/Documentation/html/guides/pipeline-handler.html': Permission denied
rm: cannot remove 'build/Documentation/html/guides/introduction.html': Permission denied
rm: cannot remove 'build/Documentation/html/objects.inv': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/contributing.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/index.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/sensor_driver_requirements.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/coding-style.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/environment_variables.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/api-html/index.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/docs.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/guides/ipa.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/guides/application-developer.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/guides/pipeline-handler.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/guides/introduction.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/guides/tracing.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/getting-started.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/lens_driver_requirements.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/_sources/python-bindings.rst.txt': Permission denied
rm: cannot remove 'build/Documentation/html/search.html': Permission denied
rm: cannot remove 'build/Documentation/html/.buildinfo': Permission denied
rm: cannot remove 'build/Documentation/html/getting-started.html': Permission denied
rm: cannot remove 'build/Documentation/html/lens_driver_requirements.html': Permission denied
rm: cannot remove 'build/Documentation/html/genindex.html': Permission denied
rm: cannot remove 'build/Documentation/html/environment_variables.html': Permission denied
rm: cannot remove 'build/Documentation/html/index.html': Permission denied
rm: cannot remove 'build/Documentation/html/sensor_driver_requirements.html': Permission denied
djaldridge@LAPTOP-4BBALQ2L:~/libcamera$ ls
COPYING.rst    LICENSES    build    libcamera    meson_options.txt  src          test
Documentation  README.rst  include  meson.build  package            subprojects  utils
djaldridge@LAPTOP-4BBALQ2L:~/libcamera$ cd ..
djaldridge@LAPTOP-4BBALQ2L:~$ cd libcamera
djaldridge@LAPTOP-4BBALQ2L:~/libcamera$ meson setup build --buildtype=release -Dpipelines=rpi/vc4 -Dipas=rpi/vc4 -Dv4l2=true -Dgstreamer=enabled -Dtest=false -Dlc-compliance=disabled -Dcam=disabled -Dqcam=disabled -Ddocumentation=disabled -Dpycamera=enabled
The Meson build system
Version: 1.2.0
Source dir: /home/djaldridge/libcamera
Build dir: /home/djaldridge/libcamera/build
Build type: native build
Project name: libcamera
Project version: 0.1.0
C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the host machine: cc ld.bfd 2.34
C++ compiler for the host machine: c++ (gcc 9.4.0 "c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Header "unistd.h" has symbol "issetugid" : NO 
Header "locale.h" has symbol "locale_t" : YES 
Header "stdlib.h" has symbol "secure_getenv" : YES 
Compiler for C supports arguments -Wno-c99-designator: NO 
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency lttng-ust found: YES 2.11.0
Program ./parser.py found: YES (/home/djaldridge/libcamera/utils/ipc/./parser.py)
Program ./generate.py found: YES (/home/djaldridge/libcamera/utils/ipc/./generate.py)
Program ./extract-docs.py found: YES (/home/djaldridge/libcamera/utils/ipc/./extract-docs.py)
Program ./gen-tp-header.py found: YES (/home/djaldridge/libcamera/utils/tracepoints/./gen-tp-header.py)
Configuring version.h using configuration
Program openssl found: YES (/usr/bin/openssl)
Library atomic found: YES
Run-time dependency threads found: YES
Run-time dependency libdw found: YES 0.176
Run-time dependency libunwind found: YES 1.21
Header "execinfo.h" has symbol "backtrace" : YES 
Checking for function "dlopen" : NO 
Library dl found: YES
Run-time dependency libudev found: YES 245
Run-time dependency yaml-0.1 found: YES 0.2.2
Run-time dependency gnutls found: YES 3.6.13
Dependency libexif skipped: feature android disabled
Dependency libjpeg skipped: feature android disabled
Dependency libevent_pthreads skipped: feature cam disabled
Dependency libevent_pthreads skipped: feature lc-compliance disabled
Run-time dependency libtiff-4 found: YES 4.1.0
Dependency gtest skipped: feature lc-compliance disabled
Dependency qt5 (modules: Core, Gui, Widgets) skipped: feature qcam disabled
Run-time dependency glib-2.0 found: YES 2.64.6
Run-time dependency gstreamer-video-1.0 found: YES 1.16.3
Run-time dependency gstreamer-allocators-1.0 found: YES 1.16.3
Run-time dependency python3 found: YES 3.8
pybind11-config found: NO
Found CMake: /usr/bin/cmake (3.16.3)
DEPRECATION: CMake support for versions <3.17 is deprecated since Meson 0.62.0.
|
|   However, Meson was only able to find CMake 3.16.3.
|
|   Support for all CMake versions below 3.17.0 will be removed once
|   newer CMake versions are more widely adopted. If you encounter
|   any errors please try upgrading CMake to a newer version first.

Run-time dependency pybind11 found: NO (tried pkgconfig, config-tool and cmake)

src/py/libcamera/meson.build:10:15: ERROR: Dependency "pybind11" not found, tried pkgconfig, config-tool and cmake

A full log can be found at /home/djaldridge/libcamera/build/meson-logs/meson-log.txt
djaldridge@LAPTOP-4BBALQ2L:~/libcamera$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Documentation/environment_variables.rst

no changes added to commit (use "git add" and/or "git commit -a")
djaldridge@LAPTOP-4BBALQ2L:~/libcamera$ git show HEAD --stat
commit baaad1bf9e2acb3ab721945041ef46496951c04c (HEAD -> master, origin/master, origin/HEAD)
Author: Kieran Bingham <kieran.bingham@ideasonboard.com>
Date:   Mon Jul 10 17:35:09 2023 +0100

    utils: checkstyle.py: Check trailers for Amendment commits
    
    The commit trailers are checked as part of processing the commit message
    with the newly introduced TrailersChecker.
    
    This relies on the trailers property being correctly exposed by the
    Commit object, and is implemented for the base Commit but not processed
    for Amendment commits.
    
    Refactor the trailer property handling to a helper function in the base
    Commit class and make use of it with a newly added call to obtain the
    existing Trailers from the most recent commit when using Amendment.
    
    Reviewed-by: Umang Jain <umang.jain@ideasonboard.com>
    Tested-by: Jacopo Mondi <jacopo.mondi@ideasonboard.com>
    Signed-off-by: Kieran Bingham <kieran.bingham@ideasonboard.com>

 utils/checkstyle.py | 26 ++++++++++++++++++--------
 1 file changed, 18 insertions(+), 8 deletions(-)
djaldridge@LAPTOP-4BBALQ2L:~/libcamera$

**Comment by Daifaizonaldridge** [comment]
this is the output for the commands you gave.
