### ISSUE TITLE
libcamera.utils not found when using python

### ISSUE THREAD

**Issue by cogthought** [raspberrypi/libcamera#76]
using the python libcamera continuous capture example

Error
./test_cam_lib.2.py", line 13, in <module>
    import libcamera.utils
ModuleNotFoundError: No module named 'libcamera.utils'

Not should how to install the licamera.utils for python3. 

Using a Raspberry Pi CM4.

Thanks,
Robert

**Comment by naushir** [comment]
If you re-install a fresh OS image, do you still get is problem?  If not, I'll close this down otherwise we can investigate further.

**Comment by naushir** [comment]
Closing now.... Please reopen if this is still causing you issues on a fresh OS image.
