### ISSUE TITLE
ScalerCrop

### ISSUE THREAD

**Issue by valdemaria** [raspberrypi/libcamera#78]
Hi,

I'm using gstlibcamera with a HQ picam on a CM4. 

I try to implement a digital zoom, so I want to use the libcamera::controls::scalercrop. 

I use the libcamerasrc like that : libcamerasrc ! video/x-raw,width=2048,height=1536,framerate=30/1,format=YUY2,interlace-mode=(string)progressive,colorimetry=(string)bt709
I use this capture resolution because I need 30fps and 2x2 binned mode to get frame from all the sensor. 

after this, I use a videoscale to set resolution to 1920x1080, 1280/720 or 640/360 ( so, from a pixel-aspect-ratio 3/4to 16/9) 

I used a pimped gstlibcamera lib, because i need to set controls, so I have implemented functions to set and get controlList. 

I am able to set and get all the controls (like brightness, contrast, AeExposure ... ), except scalercrop, witch is not working everytime. 

I would like to now if there is something wrong on my way of using scalercrop, to be used while i'm streaming. 

Thanks for your help :) !

**Comment by naushir** [comment]
I think you might be better posting this question to the [libcamera mailing list](https://lists.libcamera.org/listinfo/libcamera-devel).  The gstreamer component is not something that we develop or maintian.
