### ISSUE TITLE
Stereo Camera Support

### ISSUE THREAD

**Issue by htchr** [raspberrypi/libcamera#81]
Hello,
I'm working with a raspberry pi compute module 4, I have 2 Arducams plugged into the CSI ports.
Is there anyway to synchronize the cameras for stereo vision? 
Thanks,

**Comment by naushir** [comment]
Libcamera itself does not have direct stereo support.  Instead, you will either have to write an application that opens 2x libcamera instances and combine the outputs into a single side-by-side buffer if needed.  Alternatively, you can run an 2x instances of existing application in separate processes and combine the frames as a postprocessing step.

In either case, there is no software synchronisation between the two cameras.  You will have to rely on hardware synchronisation instead, see [here](https://www.raspberrypi.com/documentation/accessories/camera.html#synchronous-captures) for details on how to do this with a Raspberry Pi official camera.  I cannot advise on how to do this with an Arducam camera, please contact their support forums for further help.
