### ISSUE TITLE
The problem that status_.targetExposureValue in agc_channel.cpp is always 0

### ISSUE THREAD

**Issue by tom-ard** [raspberrypi/libcamera#83]
I found that the data in status_ are obtained from filtered, but targetExposureValue is obtained from target_.Is this intentional?
![image](https://github.com/raspberrypi/libcamera/assets/100827463/d21e20c2-00ec-46d1-b262-2a024ea2a3c5)

This will cause status_.targetExposureValue to always have a value of 0.
![image](https://github.com/raspberrypi/libcamera/assets/100827463/f23b5e2c-4657-4f23-aa69-e7c30818f0ad)

Since status_.targetExposureValue is always 0, lockCount has never been updated.
![image](https://github.com/raspberrypi/libcamera/assets/100827463/1a1c4544-526b-46cd-9499-c0c5e9743459)

**Comment by naushir** [comment]
This seems intentional to me.  @davidplowman can you confirm?

**Comment by davidplowman** [comment]
Thanks for reporting this. Indeed I think it got broken when the filtering and digital gain calculations were re-ordered.

There's a fix [here](https://github.com/raspberrypi/libcamera/commit/f32ccfc419c471e18a181f1adb8a3b61eca872f6) on the next_integrate branch. I've also sent a patch to the libcamera mailing list.

There should probably be a Picamera2 test to check that 'AeLocked' does seem to get set eventually. Obviously not until this change has got merged, though!!

**Comment by tom-ard** [comment]
I tested your modification and the problem was solved. Thanks.

**Comment by naushir** [comment]
Changes should be merged soon.  Resolving now.
