### ISSUE TITLE
meson setup build fails

### ISSUE THREAD

**Issue by JohnGaby** [raspberrypi/libcamera#86]
I am trying to follow the build instructions but when I run:

meson setup build

it fails with the following error:

meson.build:264:7: ERROR: python3 is missing modules: ply, yaml

I have tried to find a way to install those but the only commands I find use pip which is apparently not allowed since I am using apt.

Any suggestions on how I can fix this?

**Comment by JohnGaby** [comment]
Thanks

**Comment by naushir** [comment]
@darkorb thanks for the solution.  Closing this now.
