### ISSUE TITLE
Format conversions handled on ARM not on ISP?

### ISSUE THREAD

**Issue by schoolpost** [raspberrypi/libcamera#93]
https://github.com/raspberrypi/libcamera/blob/563cd78e1c9858769f7e4cc2628e2515836fd6e7/src/libcamera/pipeline/rpi/pisp/pisp.cpp#L312

I've recently been experimenting with streaming ISP output to OpenGL textures, some of my early tests demonstrated various performance statistics based on the selected ISP format. 

I'm using a Pi5 with HQ camera and latest Bookworm. 

Initially because there are no native YUV formats in OpenGL I had opted to use BGR888 format and noticed subpar performance on the OpenGL side, which later prompted me to investigate using using a 32bit RGBA ( XBRG8888 )  style pixel format as this may be better optimized on the GPU side. 

This change in pixel format resulted in much improved opengl performance, but I saw quite an uptick in cpu usage by the libcamera application...which brings me here where looking into the pisp.cpp and noticed many pixel format conversions that appear to be happening via cpu? why is the ISP not handling this? What are the native ISP formats that would result in the least amount of cpu usage? only YUV420?

**Comment by naushir** [comment]
The ISP cannot currently support native 32-bit RGBX output formats in hardware.  So this has to be done in software with the function you pointed to above, which does a RGB24->RGB32 conversion in software.  This is not too taxing as it's only really adjusting the pixel packing.  All other formats (YUV420/422/444, RGB24, etc.) are handled directly in hardware.  You can find the complete list of native supported formats [here](https://datasheets.raspberrypi.com/camera/raspberry-pi-image-signal-processor-specification.pdf).
