### ISSUE TITLE
New version of python3-libcamera dependency error

### ISSUE THREAD

**Issue by tom-ard** [raspberrypi/libcamera#94]
When I was using "picamera2", the following error occurred:
![image](https://github.com/raspberrypi/libcamera/assets/100827463/03bf656a-e959-458f-8497-8cc4f502f7ce)

My current python3-libcamera version
![image](https://github.com/raspberrypi/libcamera/assets/100827463/6dd333d6-b3b1-45e8-a21e-fc82a4bd4349)

You can see through the ldd command that the dynamic library depends on libpisp1.0.0
![image](https://github.com/raspberrypi/libcamera/assets/100827463/cbfb51f3-c6b4-4ad9-9aa6-a3e02b7eed56)

**Comment by tom-ard** [comment]
Thanks for the reminder, I found the cause of the problem.
This was caused by installing libcamera under /usr/local when I compiled libcamera before.

**Comment by davidplowman** [comment]
Glad it's working now. I don't know if it helps, but I quite often "apt purge" the various system camera packages and applications, just to be sure I can never accidentally pick them up...!
