### ISSUE TITLE
can't open stream on remote device

### ISSUE THREAD

**Issue by cohen-sydney** [raspberrypi/libcamera#97]
I have a stream running on my Rpi using the command

libcamera-vid -t 0 --inline --listen -o tcp://192.168.104.217:8888

on the same device I can open the stream using VLC command
tcp/h264://192.168.104.217:8888

on my Mac I does not open the error.

Your Input cant be opened.

any ideas??

**Comment by cohen-sydney** [comment]
got it going with this command

libcamera-vid -t 0 --inline -o - | cvlc stream:///dev/stdin --sout '#rtp{sdp=rtsp://:8554/stream1}' :demux=h264

**Comment by cohen-sydney** [comment]
and the vlc works picking it up with rtsp://ip-of-device:8554/stream1

**Comment by naushir** [comment]
Good to know it is working!
